services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080

    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt

